apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: demo-ruby
  name: ruby
  namespace: parca
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-ruby
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-ruby
    spec:
      containers:
      - image: parca-demo:ruby
        name: python
        resources:
          limits:
            cpu: "100m"
            memory: "256Mi"
