apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: demo-deno
  name: deno
  namespace: parca
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-deno
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-deno
    spec:
      containers:
      - image: parca-demo:deno
        name: deno
        resources:
          limits:
            cpu: '100m'
            memory: '256Mi'
