FROM debian:stable as builder
RUN apt-get update && apt-get install build-essential clang -y

ARG CLANG_FLAGS

WORKDIR /app

COPY main.cpp .

RUN clang++ ${CLANG_FLAGS} -o parca-demo main.cpp

FROM debian:stable-slim as runner
RUN apt-get update && apt-get install libc6-dbg libstdc++6-10-dbg -y

COPY --from=builder /app/parca-demo .

CMD ["./parca-demo"]
