# vim: ft=dockerfile
FROM docker.io/ibm-semeru-runtimes:open-11-jdk AS build

WORKDIR /src

COPY gradle ./gradle
COPY build.gradle settings.gradle gradlew ./
RUN ./gradlew --version

COPY . /src
RUN ./gradlew build --no-daemon

FROM docker.io/ibm-semeru-runtimes:open-11-jre

WORKDIR /app

COPY --from=build /src/build/libs/demo-0.0.1-SNAPSHOT.jar /app/demo.jar

ENTRYPOINT ["java", "-XX:+PerfTool", "-jar", "/app/demo.jar"]
