/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DemoJNI */

#ifndef _Included_DemoJNI
#define _Included_DemoJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DemoJNI
 * Method:    nativeA1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DemoJNI_nativeA1
  (JNIEnv *, jobject);

/*
 * Class:     DemoJNI
 * Method:    nativeA2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DemoJNI_nativeA2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
