apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: demo-mojo
  name: mojo
  namespace: parca
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-mojo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-mojo
    spec:
      containers:
        - image: parca-demo:mojo
          name: mojo
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
